class Collections:
    USERS = "users"
    PARKING_RECORDS = "parking_records"
    PRICING_RULES = "pricing_rules"
    SETTINGS = "settings"
    AUDIT_LOGS = "audit_logs"


class UserRoles:
    ADMIN = "admin"
    GUARD = "guard"
    ALL = (ADMIN, GUARD)


class UserStatus:
    ACTIVE = "active"
    INACTIVE = "inactive"
    DELETED = "deleted"
    ALL = (ACTIVE, INACTIVE, DELETED)


class AuditActions:
    USER_LOGIN = "USER_LOGIN"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_PASSWORD_RESET = "USER_PASSWORD_RESET"


class ErrorCodes:
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
