class Collections:
    USERS = "users"
    PARKING_RECORDS = "parking_records"
    PRICING_RULES = "pricing_rules"
    SETTINGS = "settings"
    AUDIT_LOGS = "audit_logs"


class UserRoles:
    ADMIN = "admin"
    GUARD = "guard"
    ALL = (ADMIN, GUARD)


class UserStatus:
    ACTIVE = "active"
    INACTIVE = "inactive"
    DELETED = "deleted"
    ALL = (ACTIVE, INACTIVE, DELETED)


class VehicleTypes:
    BIKE = "bike"
    CAR = "car"
    ALL = (BIKE, CAR)


class ParkingStatus:
    ACTIVE = "active"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    DELETED = "deleted"
    ALL = (ACTIVE, COMPLETED, CANCELLED, DELETED)
    VISIBLE = (ACTIVE, COMPLETED, CANCELLED)


class PaymentMethods:
    CASH = "cash"


class PricingTypes:
    FIXED = "fixed"
    HOURLY = "hourly"
    ALL = (FIXED, HOURLY)


class Currencies:
    PKR = "PKR"


class AuditActions:
    USER_LOGIN = "USER_LOGIN"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_PASSWORD_RESET = "USER_PASSWORD_RESET"
    VEHICLE_ENTRY_CREATED = "VEHICLE_ENTRY_CREATED"
    VEHICLE_EXIT_COMPLETED = "VEHICLE_EXIT_COMPLETED"
    PARKING_RECORD_UPDATED = "PARKING_RECORD_UPDATED"
    PARKING_RECORD_DELETED = "PARKING_RECORD_DELETED"


class ErrorCodes:
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    DUPLICATE_ACTIVE_VEHICLE = "DUPLICATE_ACTIVE_VEHICLE"
    PARKING_RECORD_NOT_FOUND = "PARKING_RECORD_NOT_FOUND"
    VEHICLE_ALREADY_COMPLETED = "VEHICLE_ALREADY_COMPLETED"
    PRICING_RULE_NOT_FOUND = "PRICING_RULE_NOT_FOUND"
